### ISSUE TITLE
Rename the default branch of this repo from `master` to `main`

### ISSUE THREAD

**Issue by rsimha** [ampproject/wg-viewers#6]
See https://github.com/ampproject/amphtml/issues/32195 for more details

**Comment by ericfs** [comment]
Passing over to @Enriqe who is the facilitator now.

**Comment by Enriqe** [comment]
Done

![image](https://user-images.githubusercontent.com/5449100/114080278-12863600-9860-11eb-9a33-9612ecbbd2fc.png)


```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
